from __future__ import with_statement
import os, json
from fabric.api import run, local, settings, abort, env, cd, lcd
from fabric.operations import put

common_config = json.load(open('config.common.json', 'r'))
aws_bucket = common_config['AWS_BUCKET']

def gen_configs():
  'Generate config.dev.js and config.prod.js for node and chrome.'
  for mode in ('dev', 'prod'):
    config_json = json.load(open('config.%s.json' % mode, 'r'))
    config_dict = dict(config_json)
    config_dict.update(common_config)
    config_js = """\
    var %s_config = %s;
    if (typeof exports != undefined)
      module.exports = %s_config;
    """ % (mode, json.dumps(config_dict), mode)
    for target_dir in ('chrome', 'node'):
      with open(os.path.join(target_dir, 'config.%s.js' % mode), 'w') as out_stream:
        out_stream.write(config_js)

def upload_assets():
  'Upload the assets in assets/ to the S3 bucket specified in the config.'
  for asset in os.listdir('assets'):
    local('aws put --public %s/%s assets/%s' % (aws_bucket, asset, asset))

def generated_files():
  "Yields a list of all files generated by `fab gen' for cleaning purposes."
  for dir in ('chrome', 'node'):
    for mode in ('dev', 'prod'):
      yield '%s/config.%s.js' % (dir, mode)
  yield 'node/templates/post.mustache'
  yield 'chrome/post.mustache'
  yield 'chrome/manifest.json'

def clean():
  'Remove all generated assets.'
  for asset in generated_files():
    local('rm %s' % asset)

def copy_common_files():
  'Copy files from common/ to their appropriate places in node and chrome.'
  local('cp common/post.mustache node/templates/')
  local('cp common/post.mustache chrome/')

def chrome_compile():
  'Compile the mustache templates for chrome.'
  with lcd('chrome'):
    local('node compile.js')

def copy_chrome_scripts():
  'Copy scripts from assets/ to chrome/ according to chrome/assetScripts.json.'
  for script in json.load(open('chrome/assetScripts.json')):
    local('cp assets/%s chrome/' % script)

def gen():
  'Generate assets for node and chrome.'
  gen_configs()
  copy_common_files()
  chrome_compile()
  copy_chrome_scripts()

def setup_linode():
  env.host_string = 'linode'
  env.source_dir = '/home/wcauchois/Code/w.s/node'
  env.target_dir = 'w.s/node'

def linode_deploy():
  setup_linode()
  for filename in os.listdir(env.source_dir):
    if not filename.startswith('.') and not filename == 'node_modules':
      put(os.path.join(env.source_dir, filename),
        os.path.join(env.target_dir, filename))
